name: Backend Continuous Integration

on:
  # This allows running on-demand
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      # This will only run on changes to the backend code
      - "starter/backend/**"

env:
  PYTHON_VERSION: 3.11

jobs:
  lint_job:
    name: Backend Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install flake8  
          pipenv install

      - name: Run lint
        run: |
          pipenv run lint

  test_job:
    name: Backend run test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Run tests
        run: |
          pipenv run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint_job
      - test_job
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Build
        run: docker build -t my-backend-app
